### ISSUE TITLE
OSPP 官网的 Logo 似乎是新的，没有同步过来

### ISSUE THREAD

**Issue by stevending1st** [opensource-f2f/artwork#10]

**Comment by LinuxSuRen** [comment]
他们好像是每年都会稍微改变下

**Comment by stevending1st** [comment]
> 他们好像是每年都会稍微改变下

我是说他们官网上 osf2f 的 Logo 是新的。

**Comment by LinuxSuRen** [comment]
https://summer-ospp.ac.cn/ 这里的吗？上面开源面对面的logo就是从这个仓库出来的。

**Comment by stevending1st** [comment]
> https://summer-ospp.ac.cn/ 这里的吗？上面开源面对面的logo就是从这个仓库出来的。

可能是网络问题没有加载出来，抱歉。
